server:
  port : 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/giramundo_db
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
application:
  app:
    jwtSecret: 06f513db-d0c3-4e40-9ce1-d1a73f24b655
    jwtExpirationMs: 86400000